### ISSUE TITLE
CI coverage gauge doesn't work when mean !=0

### ISSUE THREAD

**Issue by jzelner** [epibayes/epitutorials#7]
If you change the sample mean, the coverage is wrong:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/136323/180012562-b9620a53-9201-470d-b394-2332bd3973bc.png">

Also gives an NA error if there is no value - not sure if there's a simple way to fix that?

Not sure if this is in the simulation or UI code?

**Comment by choisteph** [comment]
most of these issues might be happening because the original inputs (nsamp, mean, sd) were "duplicated" aka each time nsamp, mean, and sd need to be used, a "new" set of inputs (nsamp2, mean2, sd2, etc.) were created. no way to get around this because shiny builds and binds the inputs to an HTML ID (and the same ID can't be used more than once). If you could go in and check the numbers and code, that would probably be helpful.

**Comment by choisteph** [comment]
ok i think i found the issue with the sample coverage (forgot to update one of the `input$mean` calls to `input$mean4`). please check [this commit](https://github.com/epibayes/epitutorials/commit/53960a6ad24990a55ddd62fc82752d76dd4149c3) to see if it's working correctly.

Will look into to fixing the no value issue.

**Comment by choisteph** [comment]
If NA, mean (number input) will default back to 0. Please check [this commit](https://github.com/epibayes/epitutorials/commit/8097786736fee7d6e017a0d1dad98aa35df19508).

**Comment by jzelner** [comment]
Looks good; thanks!
